import ("m3fe")
import ("m3make")
import ("m3link")
import ("m3ir")
import ("m3C")

% generate version info
include ("version.quake")
version_make ("Version")
c_source ("Version")

Module ("Arg")
Module ("Msg")
Module ("Builder")
Module ("Dirs")
Module ("Utils")
Module ("Makefile")

Module ("M3Build")
Module ("M3Options")
Module ("M3Loc")
Module ("M3Req")
Module ("M3Unit")
Module ("M3Backend")

implementation ("Main")

build_standalone ()
Program ("m3neos")
