import("neolib")
import("m3ir")
import("m3make")
import("llvm18api")
include("version.quake")
version_impl("Version")

module("LLVM_WASM")
module("TypeComp")

implementation("Main")

%build_standalone()

Program("m3llwasm")
